[cbc] Add suffix to command implementations
To avoid some name clashes

tools\cbc.cc(826) : error C2872: 'hash' : ambiguous symbol
        could be 'tools\cbc.cc(408) : bool hash(libcouchbase_t,std::list<_Ty> &)'
        with
        [
            _Ty=std::string
        ]
        or       'C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\xfunctional(763) : std::hash'

Change-Id: I50184e8c8a11b3931eaa4cd1511a2bccb2d8966b
Reviewed-on: http://review.couchbase.org/17005
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Trond Norbye <trond.norbye@gmail.com>