Fix compiler warning caused by UV_VERSION macro
In file included from plugins/io/libuv/plugin-internal.h:31:0,
                 from plugins/io/libuv/plugin-libuv.c:18:
plugins/io/libuv/libuv_compat.h:24:23: error: "UV_VERSION_PATCH" is not defined [-Werror=undef]
                      (UV_VERSION_PATCH))
                       ^
plugins/io/libuv/libuv_compat.h:82:5: note: in expansion of macro 'UV_VERSION'
 #if UV_VERSION < 0x000900
     ^
plugins/io/libuv/libuv_compat.h:24:23: error: "UV_VERSION_PATCH" is not defined [-Werror=undef]
                      (UV_VERSION_PATCH))
                       ^
plugins/io/libuv/libuv_compat.h:90:5: note: in expansion of macro 'UV_VERSION'
 #if UV_VERSION < 0x000b00
     ^
plugins/io/libuv/libuv_compat.h:24:23: error: "UV_VERSION_PATCH" is not defined [-Werror=undef]
                      (UV_VERSION_PATCH))
                       ^
plugins/io/libuv/plugin-libuv.c:66:5: note: in expansion of macro 'UV_VERSION'
 #if UV_VERSION < 0x000900
     ^

Change-Id: Id8cf8c6454a201a386f7043a8b692a78f9750861
Reviewed-on: http://review.couchbase.org/30654
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Brett Lawson <brett19@gmail.com>