CCBC-954: define EFTYPE error code if it does not exist
libuv have defined new error code, which is not portable, so we have to add it to our list of exceptions

  plugins/io/libuv/libuv_compat.h: In function 'uv_uv2syserr':
  plugins/io/libuv/libuv_compat.h:200:7: error: 'EFTYPE' undeclared (first use in this function); did you mean 'UV_EFTYPE'?
         UV_ERRNO_MAP(X)
         ^~~~~~~~~~~~
  plugins/io/libuv/libuv_compat.h:199:63: note: in definition of macro 'X'
         #define X(name, desc) if (status == UV_##name) { return name; }
                                                                 ^~~~
  plugins/io/libuv/libuv_compat.h:200:7: note: each undeclared identifier is reported only once for each function it appears in
         UV_ERRNO_MAP(X)
         ^~~~~~~~~~~~
  plugins/io/libuv/libuv_compat.h:199:63: note: in definition of macro 'X'
         #define X(name, desc) if (status == UV_##name) { return name; }

Related libuv change: https://github.com/libuv/libuv/commit/fe3fbd63e5dfe26c473cdd422ad216a14ae2d7e4

Change-Id: If1603dc4b7dbf65ec64fc7a5af50c3a9081166e0
Reviewed-on: http://review.couchbase.org/96873
Reviewed-by: Brett Lawson <brett19@gmail.com>
Tested-by: Build Bot <build@couchbase.com>