Add missing <cerrno> include for Apple clang 12
When compiling with Apple clang 12.0.0 (XCode 12.1, macOS Catalina
10.15.7) the following errors are seen:

    libcouchbase/src/lcbio/rw-inl.h:75:22: error: use of undeclared identifier 'EWOULDBLOCK'
                    case EWOULDBLOCK:
                         ^
    libcouchbase/src/lcbio/rw-inl.h:78:22: error: use of undeclared identifier 'EINTR'
                    case EINTR:
                         ^
Fix by #including <cerrno>

Change-Id: I628c586ee1fcd17c1713c8b5289ce0123a5829a2
Reviewed-on: http://review.couchbase.org/c/libcouchbase/+/139476
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Sergey Avseyev <sergey.avseyev@gmail.com>