Fix build failure on windows
tests\regression-unit-test.cc(130): error C2057: expected constant expression
tests\regression-unit-test.cc(130): error C2466: cannot allocate an array of constant size 0
tests\regression-unit-test.cc(130): error C2133: 'cmds' : unknown size
tests\regression-unit-test.cc(131): error C2057: expected constant expression
tests\regression-unit-test.cc(131): error C2466: cannot allocate an array of constant size 0
tests\regression-unit-test.cc(131): error C2133: 'cmdlist' : unknown size
tests\regression-unit-test.cc(136): error C2070: 'lcb_get_cmd_t []': illegal sizeof operand
tests\regression-unit-test.cc(138): warning C4018: '<' : signed/unsigned mismatch

Change-Id: Ia6f3521247576de7edcb133a09ef98c9e1c9e111
Reviewed-on: http://review.couchbase.org/30031
Tested-by: Sergey Avseyev <sergey.avseyev@gmail.com>
Reviewed-by: Brett Lawson <brett19@gmail.com>